name: untitled1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphview: ^1.3.2
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  dart_openai: ^5.1.0
  diacritic: ^0.1.3
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.5
  path_provider: ^2.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/assistant/pnj.png
